require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/employers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Employer. As you add validations to Employer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Employer.create! valid_attributes
      get employers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      employer = Employer.create! valid_attributes
      get employer_url(employer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_employer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      employer = Employer.create! valid_attributes
      get edit_employer_url(employer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Employer" do
        expect {
          post employers_url, params: { employer: valid_attributes }
        }.to change(Employer, :count).by(1)
      end

      it "redirects to the created employer" do
        post employers_url, params: { employer: valid_attributes }
        expect(response).to redirect_to(employer_url(Employer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Employer" do
        expect {
          post employers_url, params: { employer: invalid_attributes }
        }.to change(Employer, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post employers_url, params: { employer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested employer" do
        employer = Employer.create! valid_attributes
        patch employer_url(employer), params: { employer: new_attributes }
        employer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the employer" do
        employer = Employer.create! valid_attributes
        patch employer_url(employer), params: { employer: new_attributes }
        employer.reload
        expect(response).to redirect_to(employer_url(employer))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        employer = Employer.create! valid_attributes
        patch employer_url(employer), params: { employer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested employer" do
      employer = Employer.create! valid_attributes
      expect {
        delete employer_url(employer)
      }.to change(Employer, :count).by(-1)
    end

    it "redirects to the employers list" do
      employer = Employer.create! valid_attributes
      delete employer_url(employer)
      expect(response).to redirect_to(employers_url)
    end
  end
end
