require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/job_descriptions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # JobDescription. As you add validations to JobDescription, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JobDescription.create! valid_attributes
      get job_descriptions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      job_description = JobDescription.create! valid_attributes
      get job_description_url(job_description)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_job_description_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      job_description = JobDescription.create! valid_attributes
      get edit_job_description_url(job_description)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JobDescription" do
        expect {
          post job_descriptions_url, params: { job_description: valid_attributes }
        }.to change(JobDescription, :count).by(1)
      end

      it "redirects to the created job_description" do
        post job_descriptions_url, params: { job_description: valid_attributes }
        expect(response).to redirect_to(job_description_url(JobDescription.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JobDescription" do
        expect {
          post job_descriptions_url, params: { job_description: invalid_attributes }
        }.to change(JobDescription, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post job_descriptions_url, params: { job_description: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested job_description" do
        job_description = JobDescription.create! valid_attributes
        patch job_description_url(job_description), params: { job_description: new_attributes }
        job_description.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the job_description" do
        job_description = JobDescription.create! valid_attributes
        patch job_description_url(job_description), params: { job_description: new_attributes }
        job_description.reload
        expect(response).to redirect_to(job_description_url(job_description))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        job_description = JobDescription.create! valid_attributes
        patch job_description_url(job_description), params: { job_description: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested job_description" do
      job_description = JobDescription.create! valid_attributes
      expect {
        delete job_description_url(job_description)
      }.to change(JobDescription, :count).by(-1)
    end

    it "redirects to the job_descriptions list" do
      job_description = JobDescription.create! valid_attributes
      delete job_description_url(job_description)
      expect(response).to redirect_to(job_descriptions_url)
    end
  end
end
