require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/job_applications", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # JobApplication. As you add validations to JobApplication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JobApplication.create! valid_attributes
      get job_applications_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      job_application = JobApplication.create! valid_attributes
      get job_application_url(job_application)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_job_application_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      job_application = JobApplication.create! valid_attributes
      get edit_job_application_url(job_application)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JobApplication" do
        expect {
          post job_applications_url, params: { job_application: valid_attributes }
        }.to change(JobApplication, :count).by(1)
      end

      it "redirects to the created job_application" do
        post job_applications_url, params: { job_application: valid_attributes }
        expect(response).to redirect_to(job_application_url(JobApplication.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JobApplication" do
        expect {
          post job_applications_url, params: { job_application: invalid_attributes }
        }.to change(JobApplication, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post job_applications_url, params: { job_application: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested job_application" do
        job_application = JobApplication.create! valid_attributes
        patch job_application_url(job_application), params: { job_application: new_attributes }
        job_application.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the job_application" do
        job_application = JobApplication.create! valid_attributes
        patch job_application_url(job_application), params: { job_application: new_attributes }
        job_application.reload
        expect(response).to redirect_to(job_application_url(job_application))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        job_application = JobApplication.create! valid_attributes
        patch job_application_url(job_application), params: { job_application: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested job_application" do
      job_application = JobApplication.create! valid_attributes
      expect {
        delete job_application_url(job_application)
      }.to change(JobApplication, :count).by(-1)
    end

    it "redirects to the job_applications list" do
      job_application = JobApplication.create! valid_attributes
      delete job_application_url(job_application)
      expect(response).to redirect_to(job_applications_url)
    end
  end
end
